name: on_screen_ruler
description: Draw 8x8 pixel Square by default on top of your apps by double click on appbar of your app.
version: 0.0.1
homepage: https://github.com/aldychris/on_screen_ruler.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
#  flutter_test:
#    sdk: flutter